apiVersion: v1
kind: Service
metadata: 
  name: host3-service
spec:
  selector:
    app: host3
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2553
      targetPort: 2553
      name: akka-port
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
      name: http-port
    - protocol: TCP
      port: 9085
      targetPort: 9085
      name: management-port
    - protocol: TCP
      port: 4003
      targetPort: 4003
      nodePort: 30003
      name: debug-port