apiVersion: v1
kind: Service
metadata: 
  name: host2-service
spec:
  selector:
    app: host2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2552
      targetPort: 2552
      name: akka-port
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
      name: http-port
    - protocol: TCP
      port: 9085
      targetPort: 9085
      name: management-port
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 30002
      name: debug-port