#minikube service host3-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: host3-deployment
  labels:
    app: host3
    podapp: routes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host3
  template:
    metadata:
      labels:
        app: host3
        podapp: routes
    spec:
      serviceAccountName: sa-host3
      containers:
      - name: host3
        image: host-0
        ports:
        - name: akka
          containerPort: 2553
          protocol: TCP
        - name: http
          containerPort: 8083
          protocol: TCP  
        - name: management
          containerPort: 9085
          protocol: TCP
        env:
            - name: DEBUG_PORT
              value: "4003"
            - name: CLUSTER_HOST
              value: "host3-service.default.svc.cluster.local"
            - name: CLUSTER_PORT
              value: "2553"
            - name: HTTP_PORT
              value: "8083"  
        imagePullPolicy: Never