apiVersion: v1
kind: Service
metadata: 
  name: host1-service
spec:
  selector:
    app: host1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2551
      targetPort: 2551
      name: akka-port
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
      name: http-port
    - protocol: TCP
      port: 9085
      targetPort: 9085
      name: management-port
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30001
      name: debug-port