---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-host3
  labels:
    app: host3
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: host3-r-cluster-managers
  labels:
    app: host3
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - pods/log
      - deployments
    verbs: 
      - get
      - watch
      - list
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: host3-rb-cluster-managers
  labels:
    app: host3
roleRef:
  kind: Role
  name: host3-r-cluster-managers
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sa-host3
  
---